commands:
    path:  /commands
    defaults: { _controller: 'TMB\TweetYourCode\Controller\CommandsController::commandsAction'}
    methods: [GET]

draw:
    path:  /draw/{command}
    defaults: { _controller: 'TMB\TweetYourCode\Controller\CommandsController::drawAction'}
    methods: [POST]

default:
    path:  /
    defaults: { _controller: 'TMB\TweetYourCode\Controller\DefaultController::defaultAction'}
    methods: [GET]

default_appfrontflow:
    path:  /flow
    defaults: { _controller: 'TMB\TweetYourCode\Controller\DefaultController::getAppfrontFlowAction'}
    methods: [GET]
    
default_myip:
    path:  /myip
    defaults: { _controller: 'TMB\TweetYourCode\Controller\DefaultController::getMyIpAction'}
    methods: [GET]
